### ISSUE TITLE
[BUG] The "Поточний пароль" field has validation in the "Безпека" tab

### ISSUE THREAD

**Issue by papiroskada** [fictadvisor/fictadvisor#13]
**Preconditions:**
The uaer is authorized
**Steps to reproduce**
1. Go to "Безпека" tab
2. Enter the "Поточний пароль"
3. Pay attention to validation border

**Actual result:**

![Image](https://github.com/fictadvisor/fictadvisor-web/assets/100213341/a065184e-6567-447a-a845-7e241b07df78)

![Image](https://github.com/fictadvisor/fictadvisor-web/assets/100213341/7f4b0d20-a090-4503-918c-1d07e69cec77)

**Expected result:**
There is no validation of the "Поточний пароль" field
**Environment:**
-deploy: prod, dev
-url: https://dev.fictadvisor.com/account?tab=SECURITY
-OS: Windows 10
-browser: Google Chrome 119.0.6045.200

**Comment by Markusplay** [comment]
Close as not planned by @hoshion

**Comment by Markusplay** [comment]
Rejected by @hoshion
