### ISSUE TITLE
[BUG] The teachers list is not displayed on the "Викладачі" page after removing the sorting method

### ISSUE THREAD

**Issue by kovaliovev** [fictadvisor/fictadvisor#14]
**Steps to reproduce**
1. Go to the "Викладачі" page.
2. Click on the remove button in the "Сортувати за" dropdown.
3. Reload the page.
4. Pay attention to the list of teachers.

**Actual result:**
The teachers' list is not displayed on the "Викладачі" page after removing the sorting method.

**Expected result:**
The remove button is not included in the "Сортувати за" dropdown. The user can only choose between "Іменем" and "Прізвищем" options.

![Image](https://github.com/fictadvisor/fictadvisor-web/assets/111194749/4a236f9d-b370-48e8-b653-435e73cdf7de)

**Environment:**
-deploy: prod, dev.
-url: https://fictadvisor.com/teachers
-OS: Windows 10
-browser: Google Chrome 116.0.5845.141

**Comment by Markusplay** [comment]
Fixed
