### ISSUE TITLE
[BUG] The cross icon is superimposed on the text in the "Передати права старости" window after resizing the page to 341px by 900px

### ISSUE THREAD

**Issue by IK-24KudinaDiana** [fictadvisor/fictadvisor#149]
**Preconditions:**
1. Registered headman profile;
2. Screen size: **FROM:** 341px by 900px; **TO:** 391px by 900 px;

**Steps to reproduce**
1. Open FICT Advisor https://dev.fictadvisor.com/.
2. Go to "Група" tab https://dev.fictadvisor.com/account?tab=GROUP.
3. Change the scale of the screen to 341px by 900px.
4. Click on the button "Передати старосту".
5. Pay attention to the cross icon.

**Actual result:**

![Image](https://github.com/fictadvisor/fictadvisor/assets/128691252/d06fa94e-7f21-43e8-a86f-9183855c32db)

**Expected result:**

![Image](https://github.com/fictadvisor/fictadvisor/assets/128691252/72d2c881-3d83-4e17-b168-40aadb32defe)

**Environment:**
-deploy: dev
-url: https://dev.fictadvisor.com/
-OS: Windows 11 Pro
-browser: Google Chrome 119.0.6045.124

**Comment by Markusplay** [comment]
The minimal screen size -> 360px. The lower sizes are not supported anymore
