### ISSUE TITLE
[BUG] The password field is not validated in the "Безпека" tab after entering Cyrillic characters.

### ISSUE THREAD

**Issue by IK-24KudinaDiana** [fictadvisor/fictadvisor#16]
**Preconditions:**
Registered user.

**Steps to reproduce**
1. Open FICT Advisor https://dev.fictadvisor.com/.
2. Go to "Безпека" tab.
3. Change password(Test data: new password - тест2023g).
4. Pay attention to the validation of the field.

**Actual result:**

![Image](https://github.com/fictadvisor/fictadvisor-web/assets/128691252/74a882c5-4b26-4653-8378-d06931402afd)

**Expected result:**
Cyrillic characters are not displayed in the password field in the "Безпека" tab after entering them.
**Environment:**
-deploy: prod, dev
-url: https://dev.fictadvisor.com/
-OS: Windows 11 Pro
-browser: Google Chrome 119.0.6045.124

**Comment by Markusplay** [comment]
Rejected by @hoshion
