### ISSUE TITLE
[BUG] The password field is not validated on the registration page after entering Cyrillic characters.

### ISSUE THREAD

**Issue by IK-24KudinaDiana** [fictadvisor/fictadvisor#17]
**Steps to reproduce**
1. Open FICT Advisor https://dev.fictadvisor.com/
2. Click on the "Зареєструватись" button.
3. Fill in the fields with valid data except the password.(Юзернейм - test, Прізвище - Кирилюк, Ім'я - Олександра, По батькові - Денисівна, Пошта - ciyel45613@cabose.com, Група - ІК-24, Пароль - тест2023g, Підтвердження пароля - тест2023g)
4. Click on the "Зареєструватись" button.
5. Pay attention to the site.

**Actual result:**

https://github.com/fictadvisor/fictadvisor-web/assets/128691252/722a62c4-58c2-43cd-a098-2f2606770936

![Image](https://github.com/fictadvisor/fictadvisor-web/assets/128691252/ed7f57b4-01cc-46b6-9bcf-96f64372a008)

**Expected result:**
Cyrillic characters are not displayed in the password field on the registration page after entering them.
**Environment:**
-deploy: prod, dev
-url: https://dev.fictadvisor.com/
-OS: Windows 11 Pro
-browser: Google Chrome 119.0.6045.124

**Comment by Markusplay** [comment]
Rejected by @hoshion
