### ISSUE TITLE
[BUG] Bugs on the survey page

### ISSUE THREAD

**Issue by IK-24KudinaDiana** [fictadvisor/fictadvisor#22]
There are some bugs on survey page:

## Front-end

- there is no teacher search bar

![image](https://github.com/fictadvisor/fictadvisor/assets/42845566/99832fb7-876f-40a4-a69f-7df47ada1fb3)

- should fit 4 cards

![image](https://github.com/fictadvisor/fictadvisor/assets/42845566/6edd4200-faae-4c93-8b70-2f402919a9e4)
![image](https://github.com/fictadvisor/fictadvisor/assets/42845566/360cfbe6-49be-4afb-9024-d6c6338f4a88)

- change to "ти" form

![image](https://github.com/fictadvisor/fictadvisor/assets/42845566/009bf07a-3c8b-4983-8521-5ff9e5750f12)

- 375 px, 480 px
Bug: cards stuck together and are found together; large indent to the beginning of the card.

![image](https://github.com/fictadvisor/fictadvisor/assets/42845566/e390b668-d71e-438d-aa90-64c77adec2af)
![image](https://github.com/fictadvisor/fictadvisor/assets/42845566/f70f86a3-565c-4a3b-afa9-f2156ecd84d7)

- Change "Посада" на "Викладає"

![image](https://i.imgur.com/Wl26Rhq.png)

## Back-end

- Add an ability to filter teachers for poll by Teacher role Array
https://apidev.fictadvisor.com/api#/Poll/PollController_getPollDisciplineTeachers

**Comment by hoshion** [comment]
> ![Image](https://private-user-images.githubusercontent.com/128691252/274246840-ee189d6a-59ae-4c03-914d-c35a6f0f8c68.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2NTU3NzAsIm5iZiI6MTcwNDY1NTQ3MCwicGF0aCI6Ii8xMjg2OTEyNTIvMjc0MjQ2ODQwLWVlMTg5ZDZhLTU5YWUtNGMwMy05MTRkLWMzNWE2ZjBmOGM2OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwN1QxOTI0MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMGVhZmEwYjRmMTJiMzFhZWE1OTQ5ODE2MGE4OTZkMzJjYzJkMjRjNDM5Y2Q0OTVlZmJkNDY5MDk5NWMwY2ExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yRjBX92g-R4fs0IXThsUv5UrDe8G6laOMc3OQhtkBFc) ![Image](https://private-user-images.githubusercontent.com/128691252/274246839-533d7de4-8e79-46bb-aa56-bb33827407c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2NTU3NzAsIm5iZiI6MTcwNDY1NTQ3MCwicGF0aCI6Ii8xMjg2OTEyNTIvMjc0MjQ2ODM5LTUzM2Q3ZGU0LThlNzktNDZiYi1hYTU2LWJiMzM4Mjc0MDdjMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwN1QxOTI0MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MjY2Y2RhN2VlMDY5MjM1MDRlMTk0YzE0MWY1ZDMxZGY4ZDRkN2M1NGY4YjU4YzgyNGIzZDQyNDM4ZWUyNjczJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PrjVvZw8GnTwL4e3X-ZP_5PgWVC8XgG1ieY6xb8XZ0g)
> 
> The names do not match the design

not relevant

**Comment by sifes** [comment]
when sending only a single value in array (of roles) validation error occurs
![image](https://github.com/fictadvisor/fictadvisor/assets/131526240/8e0335f4-a351-4444-aa01-d7bea9e39161)
`/v2/poll/teachers/{userId}`
