### ISSUE TITLE
[BUG] Fix bugs on subject card with type "Інша подія" after clicking on it

### ISSUE THREAD

**Issue by kol-oss** [fictadvisor/fictadvisor#23]
**Bug №1**

**Summary:** Lecturer and discipline description are visible on subject card with type "Інша подія" after clicking on it.

**Preconditions:** User is authorized, member of a group and has a permission to edit the schedule, event with type "Інша подія" is added to schedule.

**Steps to reproduce**
1. Go to Schedule page.
2. Click on event with type "Інша подія".
3. Pay attention to the "Викладач" and "Про дисципліну" fields.

**Actual result:** "Викладач" and "Про дисципліну" fields are visible.

![Image](https://github.com/fictadvisor/fictadvisor-web/assets/62239358/4b11b026-4470-4746-bdbd-dafb06e2f608)

**Expected result:** "Викладач" and "Про дисципліну" fields are invisible ([figma](https://www.figma.com/file/FHBiKogMc9VzGWojaQxA9c/%F0%9F%92%96fictadvisor?type=design&node-id=242%3A2&mode=design&t=4RhzSSDWcm5ELuVF-1)).

![Image](https://github.com/fictadvisor/fictadvisor-web/assets/62239358/706721a6-fecf-4012-9c6d-627141b6b70f)

**Bug №2**

**Summary:** Event type is thrown off on subject card with type "Інша подія" while editing it.

**Preconditions:** User is authorized, member of a group and has a permission to edit the schedule, event with type "Інша подія" is added to schedule.

**Steps to reproduce**
1. Go to Schedule page.
2. Click on event with type "Інша подія".
3. Click on change event button.
4. Pay attention to the "Тип" field.

**Actual result:** Event type is thrown off.

https://github.com/fictadvisor/fictadvisor-web/assets/62239358/f1d5f88c-82dc-4f7f-b1a0-acb231d2adad

![Image](https://github.com/fictadvisor/fictadvisor-web/assets/62239358/2cd90d29-3066-409f-bc49-26590685cbe5)

**Expected result:** Event type is saved and displayed as "Інша подія".

![Image](https://github.com/fictadvisor/fictadvisor-web/assets/62239358/4cfc0568-026e-4247-8a74-7c48853e2296)

**Bug №3**

**Summary:** Changes of event with type "Інша подія" can't be saved on Schedule page after editing.

**Preconditions:** User is authorized, member of a group and has a permission to edit the schedule, event with type "Інша подія" is added to schedule.

**Steps to reproduce**
1. Go to Schedule page.
2. Click on event with type "Інша подія".
3. Click on change event button.
4. Change any information (except of event type).
5. Click on the save button.
6. Pay attention to the event.

**Actual result:** Changes in event with type "Інша подія" can't be saved.

https://github.com/fictadvisor/fictadvisor-web/assets/62239358/e86dcd33-4ff9-403d-991c-482e1ae62372

**Expected result:** Changes in event with type "Інша подія" can be saved.

**Bug №4**

**Summary:** Change of type of the existing event into "Інша подія" isn't saved on Schedule page after editing.

**Preconditions:** User is authorized, member of a group and has a permission to edit the schedule, event with any type is added to schedule.

**Steps to reproduce**
1. Go to Schedule page.
2. Click on event with type which is not "Інша подія".
3. Click on change event button.
4. Change event type.
5. Click on the save button.
6. Pay attention to the event.

**Actual result:** Change of type of the existing event into "Інша подія" isn't saved.

https://github.com/fictadvisor/fictadvisor-web/assets/62239358/640720bc-6bec-4c1d-a1e1-832b11e1b1bb

**Expected result:** Change of type of the existing event into "Інша подія" is saved.

**Environment:**
- deploy: dev;
- url: https://dev.fictadvisor.com/schedule;
- os: Windows 10;
- browser: Google Chrome 116.0.5845.163.

**Comment by Markusplay** [comment]
> There is no "Another event" value in the disciplineType enum of UpdateEventDTO. Waiting for changes from back-end

fixed
