### ISSUE TITLE
[RESEARCH] Research Google Calendar API

### ISSUE THREAD

**Issue by hoshion** [fictadvisor/fictadvisor#255]
We will have a feature in the future that allows users to add schedules from FICT Advisor into Google Calendar. You need to research the API to get two to three variants of how to do this. Maybe, we can create templates or something else. Also, check the Google Developers forum to get information about Authorization with google. Provide essential information as google document.

**Comment by dmykyr** [comment]
[Here](https://docs.google.com/document/d/1vKyyy4w3-Op1fQIt6jqR0U_z68XYDCxR91BGtsaUjM8/edit?usp=sharing) is my research how to implement google calendar in our project
