### ISSUE TITLE
[ENHANCE] Inconsistent use of tag colors

### ISSUE THREAD

**Issue by kujo205** [fictadvisor/fictadvisor#27]
Inconsistent use of colors, tags on the schedule page for other events are of the violet colors while the tag with the same name on teacher page is red

**UPD: Don't show "Інше" and "Екзамени" tag. We must show only "Лекції", "Практики", "Лабораторні"**
![Screenshot_20231011-021058.png](https://github.com/fictadvisor/fictadvisor-web/assets/86970828/759fe4d3-f512-474b-ad4e-525ec44b1182)

Make it violet as well pls

**Comment by hoshion** [comment]
Closes from #77
