### ISSUE TITLE
[ENHANCEMENT] Update brand name on the website to FICE

### ISSUE THREAD

**Issue by Markusplay** [fictadvisor/fictadvisor#291]
![image](https://github.com/fictadvisor/fictadvisor/assets/102873980/998085a6-9afe-45ba-b68d-368be74297ec)

**Comment by IK-24KudinaDiana** [comment]
Bug#1

![Image](https://github.com/fictadvisor/fictadvisor/assets/128691252/63cde505-bddd-417b-812a-371acabd85db)

**Comment by IK-24KudinaDiana** [comment]
Needs refinement

![Image](https://github.com/fictadvisor/fictadvisor/assets/128691252/afae88a1-73d9-49c7-bb05-b99f8a299d10)
