### ISSUE TITLE
Move `subjects/{subjectId}` page to server Components

### ISSUE THREAD

**Issue by kujo205** [fictadvisor/fictadvisor#317]
With the introduction [`React Server Components`](https://nextjs.org/docs/app/building-your-application/rendering/server-components) nextjs implemented this in their newer versions and has kinda shifted their paradigm

Why server components are needed?
Let's look at a brief example: 
1. Open a main [page](https://ficeadvisor.com/) 
2. Press Ctrl + U to open page source
3. Try to find `офіційний сайт Студради ФІОТ. Опитування про викладачів, багатофункціональний розклад,`
4. You cannot find it, this is how browser crawlers see this page, they do not index main page as they could have

We can find page by this text anyways
![image](https://github.com/fictadvisor/fictadvisor/assets/86970828/f50053fb-fb45-43ca-95fa-4279bd9b6f84)

Why this is a case?
That's beacuse of the this block of [code](https://github.com/fictadvisor/fictadvisor/blob/c5ec34afc25e3f31be662e916afa15a75969c607/fictadvisor-web/src/app/page.tsx#L6) 
```ts
export const metadata: Metadata = {
  title: 'FICE Advisor',
  description:
    'Зустрічай FICE Advisor — офіційний сайт Студради ФІОТ. Опитування про викладачів, багатофункціональний розклад, керування групою, набори в наше активне ком’юніті, розіграш шар та інші інструменти — шукай саме тут!',
  openGraph: {
    title: 'FICE Advisor',
    description:
      'Зустрічай FICE Advisor — офіційний сайт Студради ФІОТ. Опитування про викладачів, багатофункціональний розклад, керування групою, набори в наше активне ком’юніті, розіграш шар та інші інструменти — шукай саме тут!',
  },
};
```

We could even make a seo better once the text was included in the source

## The task
In this task you have to rewrite  `subjects/{subjectId}` to server components, after finishing the task, make sure that the correct text is visible in page source.

**Comment by Markusplay** [comment]
https://nextjs.org/docs/app/building-your-application/rendering/server-components#using-server-components-in-nextjs
By default, Next.js uses Server Components. This allows you to automatically implement server rendering with no additional configuration, and you can opt into using Client Components when needed, see [Client Components](https://nextjs.org/docs/app/building-your-application/rendering/client-components).

So the `subjects/{subjectId}` page is RSC by default
