### ISSUE TITLE
[DESIGN] Discipline resources

### ISSUE THREAD

**Issue by hoshion** [fictadvisor/fictadvisor#339]
- **Що взагалі таке ресурс і тд?**
Це файл (який зберігається на нашому сервері, тільки пдф, докс або презентація), або посилання на файл (гугл диск, інші джерела), який містить необхідну інформацію щодо предмету. 
Приклади: силабус, методичка, комп'ютерний практикум, варіанти РГР, ТРР, МКР, презентації, посилання на відео, плейлісти, варіанти. Тобто будь що, що може знадобитися студентам. Попередньо необхідно уточнювати чи є інформація конфіденційною, чи ні. Для бази даних ресурс це назва, посилання на файл, айді предмету, айді викладача, рік і семестр

- **Нова вкладка на сторінці "Викладач" — "Ресурси"**
В ній будуть знаходитися згруповані за предметами і семестрами/роками ресурси щодо викладача. Наприклад:
Викладач Молчанова Анастасія Анатоліївна
  - Предмет "Алгоритми і структури даних 2023 1 сем":
    - Ресурс 1
    - Ресурс 2
    - Ресурс 3
  - Предмет "Комп'ютерна дискретна математика 2023 2 сем":
    - Ресурс 1
    - Ресурс 2
 і т.д.

- **Нова вкладка на сторінці "Викладач + Предмет" — "Ресурси"**
В ній будуть знаходитися згруповані за семестрами/роками ресурси щодо предмету + викладача. Наприклад:
Предмет Алгоритми і структури даних Молчанова Анастасія Анатоліївна
  - 2023 1 сем:
    - Ресурс 1
    - Ресурс 2
  - 2023 2 сем:
    - Ресурс 1
    - Ресурс 2

- **Нова вкладка на адмін панелі "Ресурси"**
Таблиця з полями "Викладач" "Предмет" "Рік і семестр", при натисканні кнопки редагування відкривається сторінка де знаходиться перелік ресурсів з можливістю додати або видалити ресурси. При натисканні кнопки створення відкривається сторінка, де знаходиться 3 дропдауни (викладач, предмет, рік і семестр) і можливість додати до цієї комбінації ресурси.

- **Хто може додавати ресурс?**
  - Адміністратори системи
  - Староста і заступник, у якого є такий предмет з таким викладачем
  - Всі інші, використовуючи відповідну кнопку на вкладці "Ресурси". У такому випадку, відповідно до сторінки, користувач дообирає необхідні дані (щоб в сумі отримати зв'язку викладач + предмет + семестр), також буде поле, куди користувач впише пояснення що це за ресурс і чому його треба додати. Після цього, нам в бота в телеграмі прилітає запит на додавання ресурсу, де ми можемо прийняти або відмовити.

**Comment by eliz-yarko** [comment]
На ФА: https://www.figma.com/file/FHBiKogMc9VzGWojaQxA9c/%F0%9F%94%A5FICE-Advisor?type=design&node-id=18226%3A57595&mode=design&t=VoCL6cTk3NECp0M0-1
Додала в адмін панелі https://www.figma.com/file/rhWB2zEPRyCR1dOI9SGhP4/%F0%9F%92%A6fictadvisor-Admin-Panel?type=design&node-id=2394%3A13795&mode=design&t=SJDZBZL2IEng4J4A-1
