### ISSUE TITLE
[DESIGN] FAQ for students

### ISSUE THREAD

**Issue by hoshion** [fictadvisor/fictadvisor#340]
- **Що таке FAQ?**
FAQ це Frequently Asked Questions, тобто питання, які часто задаються. В нашому випадку, це стосується питань загального характеру від студента до університету. Наприклад інформація щодо гуртожитків, деканату, довідок, навчання, відповідей на питання що таке <підставте сюди будь який термін>, номери кабінетів, місцерозташування, дедлайни, положення, стипендія і тд. Для бази даних це Питання, відповідь і ключові слова, які будуть відображатися у вигляді хештегів.

- **Нова сторінка "FAQ", посилання на яку буде в футері.**
На сторінці будуть можливості пошуку по питанню, сортування по питанню, фільтрація по ключовим словам, пагінація питань. Сама карточка питання буде виглядати як прямокутник, на якому написане питання, хештеги під ним, і стрілочка з боку. При натисканні на цей прямокутник розкривається відповідь. Відповідь має підтримувати основні стильові фічі (посилання, жирне, італік), думаю що можна зробити маркдаун розмітку.

- **Кілька питань під студентськими ресурсами на мейн пейджі**
Це підніме видимість наявності FAQ у нас на сайті. Можемо відображати 6 питань і відповідей і кнопку "Більше", яка пересилатиме на сторінку FAQ

- **Нова вкладка на адмін панелі - FAQ**
Сторінка з табличкою, в якій є колонки "назва питання" та "теги", також є сьорч по назві питання, мультічойс фільтрація по тегам і сортування по назві питання. Кнопка редагувати відкриває сторінку з редагуванням, де знаходиться 2 текст ерії для назви питання і відповіді та мультічойс дропдаун для тегів.

- **Хто може додавати питання?**
  - Адміністратори системи
  - Будь хто, натиснувши на кнопку "додати питання", в якій можна буде вписати питання, відповідь і ключові слова. Запит відправляється в бота, де ми вже апруваємо або ні

**Comment by eliz-yarko** [comment]
Done https://www.figma.com/design/FHBiKogMc9VzGWojaQxA9c/%F0%9F%94%A5FICE-Advisor?node-id=18226-72214

Admin pannel https://www.figma.com/design/rhWB2zEPRyCR1dOI9SGhP4/%F0%9F%92%A6fictadvisor-Admin-Panel?node-id=2474-10714&t=lTKLOrNORFttY94V-1
