### ISSUE TITLE
[DESIGN] Campus integration 

### ISSUE THREAD

**Issue by hoshion** [fictadvisor/fictadvisor#341]
Інтеграція з кампус — це досить потужна інновація на FA, оскільки це в ідеалі дозволить студентам не заходити в кампус, оскільки основні сторінки (сесія, поточний контроль, атестація) будуть на фа. Але, для початку, обмежимося тільки однією сторінкою.

- **Нова вкладка на сторінці "Акаунт" — "Сесія".**
На цій сторінці будуть відображатися спаршені оцінки з сесії на цій вкладці. Вони просто будуть у вигляді таблиці, як і в кампусі, але гарніше.

Якщо студент досі не додав логін і пароль від кампусу в ФА, на цій сторінці має відображатися кнопка "Приєднати Кампус КПІ", де будуть поля логін і пароль. В подальшому вони будуть використовуватися для парсингу сторінок.

**Comment by eliz-yarko** [comment]
https://www.figma.com/design/FHBiKogMc9VzGWojaQxA9c/%F0%9F%94%A5FICE-Advisor?node-id=299-58
