### ISSUE TITLE
[DESIGN] Teacher's schedule

### ISSUE THREAD

**Issue by hoshion** [fictadvisor/fictadvisor#342]
Вигляд розкладу для викладачів буде ідентичним до розкладу для студентів. Єдина відмінність: на карточках календаря будуть писатися групи, у яких веде викладач. Інший варіант: показувати групи у яких веде викладач після натиснення на карточку. 

Редагувати такі події, видаляти їх, оновлювати, переміщати і тд не можна буде. Можна буде фільтрувати за типом і всьо.

**Comment by eliz-yarko** [comment]
https://www.figma.com/design/FHBiKogMc9VzGWojaQxA9c/%F0%9F%94%A5FICE-Advisor?node-id=242-2

Думала що буде довго... 20 хвилин і готово

Фронт, там нові карточки для цього💋💋💋
