### ISSUE TITLE
[DESIGN] Addmission to FICE SC

### ISSUE THREAD

**Issue by hoshion** [fictadvisor/fictadvisor#343]
Колись ми хотіли зробити сторінку про студраду, в якій лаконічно розміщувалась би ця кнопка. Але враховуючи що такої сторінки немає і я не знаю коли вона буде написана і намальована, кнопка вступу буде зроблено окремо.

Кнопка буде відображатися на мейн пейджі під час набору в студраду, а також в футері (або у вкладці про нас). Це не має бути мега популярна кнопка, тому розміщувати її десь в хедері або на видному місці не обов'язково

Під час натискання кнопки відкривається окрема сторінка з формою. У формі не буде сильних особливостей: ПІБ, група, тег в телеграмі, в який відділ хочеться, мотивація, досвід. Після натискання кнопки відправити ця інформація прилітає в чат Норки студради (чат де всі голови і зами відділів)

**Comment by eliz-yarko** [comment]
https://www.figma.com/design/FHBiKogMc9VzGWojaQxA9c/%F0%9F%94%A5FICE-Advisor?node-id=18792-55841
