### ISSUE TITLE
[DESIGN] Studying Program Tab

### ISSUE THREAD

**Issue by sifes** [fictadvisor/fictadvisor#367]
- **Нова вкладка на сторінці "Акаунт" — "Навчальні програми".**
На цій сторінці будуть відображатися навчальні програми для наступних курсів/всіх курсів

Навчальні програми повинні мати вигляд подібний до того, як вони показані на картинці нижче. Кожна навчальна програма це посилання (кнопка) на сторінку з предметами на відповідний предмет

Предмети діляться на 6 груп

Математичні предмети:
1. Математичний аналіз 
2. Лінійна алгебра та аналітична геометрія
3. Теорія ймовірностей
4.  Комп'ютерна дискретна математика

Соціальні предмети (розмовні) 
1. Практичний курс іноземної мови
2. Групова динаміка і комунікації

Гуманітарні предмети
1. Українська мова за проф. спрямуванням
2. Екологіна безпека та цивільний захист
3. Історія науки і техніки
4. Основи здорового способу життя
5. Філософські основи наукового пізнання

Основи програмування:
1. Основи програмування
2. Об'єктно-орієнтоване програмування
3. Компоненти програмної інженерії
4. Бази даних
5. Системне програмування
6. Методологія та технології розроблення програмного забезпечення

Комп'ютерні науки (фізичні):  
1. Алгоритми та структури даних
2. Основи комп'ютерних систем і мереж 
3. Практикум з Linux
4. Фізичні основи комп'ютерних систем 
5. Мережі і мережні інформаційні технології

Каталоги

![image](https://github.com/fictadvisor/fictadvisor/assets/86970828/e19c3f9f-4f63-4810-8abb-68e0ee92e161)

**Comment by eliz-yarko** [comment]
https://www.figma.com/design/FHBiKogMc9VzGWojaQxA9c/%F0%9F%94%A5FICE-Advisor?node-id=299-58

Соня молодець, трохи доправила

Якщо треба додати легенду, або сортування за напрямом, кажіть

**Comment by eliz-yarko** [comment]
доробила
