### ISSUE TITLE
[BUG] The "Пароль" field has no password size limit on the account login page after entering 1000 characters

### ISSUE THREAD

**Issue by IK-24KudinaDiana** [fictadvisor/fictadvisor#4]
**Preconditions:**
Registered user account with a password of 1000 characters.
**Steps to reproduce**
1. Open FICT Advisor https://dev.fictadvisor.com/
2. Click on the "Увійти" button in the site header.
3. Enter your account details(Пошта або юзернейм - test_group, Пароль - 111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111f)
4. Pay attention to the message under the "Пароль" field.

**Actual result:**

![Image](https://github.com/fictadvisor/fictadvisor-web/assets/128691252/f2232658-deb2-4eb7-92d8-2f5490a01d28)

**Expected result:**
The password field is limited to 32 characters on the login page.
**Environment:**
-deploy: prod, dev
-url: https://dev.fictadvisor.com/
-OS: Windows 11 Pro
-browser: Google Chrome 119.0.6045.124

**Comment by Markusplay** [comment]
Close as not planned by @hoshion
