### ISSUE TITLE
[ENHANCEMENT] Add Loader to Buttons with Loading Prop

### ISSUE THREAD

**Issue by sifes** [fictadvisor/fictadvisor#456]
We need to enhance the user experience by adding a loader to buttons when a request is in progress. This loader should indicate that an action is being processed after the button is clicked, preventing users from repeatedly clicking or wondering if their action is being executed.

#### Requirements:
- Implement a `loading` prop for buttons, which will display a loader when set to `true`.
- If the existing UI library (MUI) doesn't support this by default, create a custom loader and integrate it into the buttons manually.
- Ensure the loader is visually appealing and does not interfere with the button text or layout.

#### Expected Behavior:
- The loader should replace or be displayed alongside the button text when the `loading` prop is active.
- The button should be disabled when the loader is active to prevent multiple submissions.
- The loader should be styled to match the existing design system.

**Comment by OleksandrHumeniuk** [comment]
Also add loader to buttons while registering or logging in, so the users knows that request is pending.
