### ISSUE TITLE
[BACKEND] Remove groups from graduated students

### ISSUE THREAD

**Issue by OleksandrHumeniuk** [fictadvisor/fictadvisor#470]

**Comment by dmykyr** [comment]
Наразі в нас є групи зі студентами які вже випустились, та не навчаються. Тому задачею буде видалення груп 0X та прибирання зв'язку міжз цими групами та акаунтами студентів які там навчались. Самі ж користувачі **НЕ** мають бути видаленими.

**Comment by ShavuhaS** [comment]
`DELETE FROM groups
WHERE code LIKE '%-2___' OR code LIKE '%-0_'
RETURNING *;`
