### ISSUE TITLE
[BUG] The "Новий пароль" field has no password size limit in the "Безпека" tab after entering 1000 characters

### ISSUE THREAD

**Issue by IK-24KudinaDiana** [fictadvisor/fictadvisor#5]
**Preconditions:**
Registered account.
**Steps to reproduce**
1. Open FICT Advisor https://dev.fictadvisor.com/
2. Go to "Безпека" tab.
3. Change password(Новий пароль - 111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111f)
4. Pay attention to the error message.

**Actual result:**

![Image](https://github.com/fictadvisor/fictadvisor-web/assets/128691252/03d5d2fa-dee9-465c-9509-714b16f0626c)

**Expected result:**
The "Новий пароль" field has a limit of 32 characters on the "Безпека" tab
**Environment:**
-deploy: prod, dev
-url: https://dev.fictadvisor.com/
-OS: Windows 11 Pro
-browser: Google Chrome 119.0.6045.124

**Comment by Markusplay** [comment]
Close as not planned by @hoshion
