### ISSUE TITLE
Refactor Subject entity

### ISSUE THREAD

**Issue by VlO-OlV** [fictadvisor/fictadvisor#502]
Your task will be to refactor all files, related to **Subject** entity, such as controller, service, responses, DTOs,  etc.

Your steps can be as following:
1. Check service and repository class for potential issues, misspeling or incorect code style.
2. You need to run unit tests for this service and try to enhance them, also check that all necessary service methods are covered.
3. Check responses and DTOs. As we have a lot of changes some methods can return and take undocumentated information.
4. After all responses and DTOs are checked you can separate documentation of endpoints in controller as made in [this](https://github.com/fictadvisor/fictadvisor/pull/497) pr.

**Comment by ReGeNss** [comment]
Does it make sense to do something with `SubjectByIdPipe`? For example, replace it with `ParseUUUIDPipe`, and add checks for the existence of an object with this id to the service?

**Comment by VlO-OlV** [comment]
> Does it make sense to do something with `SubjectByIdPipe`? For example, replace it with `ParseUUUIDPipe`, and add checks for the existence of an object with this id to the service?

There is no need to parse string param to uuid, because uuid is not a special type, but just a 36-symbol unique string. Moreover, it's a bad practise to move validation from pipes to services as pipes are responsible for validation (they execute before controller method to validate data, which helps to filter "incorrect" requests to endpoints)
