### ISSUE TITLE
Refactor Resource entity

### ISSUE THREAD

**Issue by VlO-OlV** [fictadvisor/fictadvisor#506]
Your task will be to refactor all files, related to **Resource** entity, such as controller, service, responses, DTOs,  etc.

Your steps can be as following:
1. Check service and repository class for potential issues, misspeling or incorect code style.
2. You need to run unit tests for this service and try to enhance them, also check that all necessary service methods are covered.
3. Check responses and DTOs. As we have a lot of changes some methods can return and take undocumentated information.
4. After all responses and DTOs are checked you can separate documentation of endpoints in controller as made in [this](https://github.com/fictadvisor/fictadvisor/pull/497) pr.

**Comment by DimaBohdan** [comment]
What do you mean about running unit tests and enhancing them? Which command does support this action?
```
npx turbo test:unit
```
or maybe:
``` 
yarn test:unit
```

**Comment by DimaBohdan** [comment]
![Знімок екрана 2024-12-08 200003](https://github.com/user-attachments/assets/caacd53e-aab2-4d75-a1e6-5e526b220269)
The next question here

**Comment by bohdanbulakh** [comment]
> ![Знімок екрана 2024-12-08 200003](https://private-user-images.githubusercontent.com/114583799/393630986-caacd53e-aab2-4d75-a1e6-5e526b220269.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM2ODQ0ODQsIm5iZiI6MTczMzY4NDE4NCwicGF0aCI6Ii8xMTQ1ODM3OTkvMzkzNjMwOTg2LWNhYWNkNTNlLWFhYjItNGQ3NS1hMWU2LTVlNTI2YjIyMDI2OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwOFQxODU2MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YjI0MzFjZWUxY2QxOWNjMzNjZmM2ZDcxYjczNDkxNTc1YjZjNDNhN2U4Zjk3M2UwNzYyYTRlMWVkYWE1NzNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.fdM6HLDs5cavu6jN3kjBLt6YO4QOZXEKAOqrN8kyDkk) The next question here

`class-validator` has decorator for checking whether it's uuid, so write this instead of `@IsAscii`:
```ts
@IsUUID(undefined, validationOptionsMsg('some message'))
```

**Comment by bohdanbulakh** [comment]
if we want to validate a property, which is instance of some class, we must add these decorators before our property:
```ts
  @ValidateNested({ each: true })
  @Type(() => UpdateResourcesDTOItem)
```
