### ISSUE TITLE
[FR] Export student's list on Group tab on Account page

### ISSUE THREAD

**Issue by hoshion** [fictadvisor/fictadvisor#52]
The task is contains of two parts:

- Create Icon Button according to the design in Figma, that triggers endpoint on the back-end:

![image](https://github.com/fictadvisor/fictadvisor/assets/42845566/d91a40bc-a115-469e-a470-6a0f0d83cd23)

- Check the efficiency of already created endpoint on the back-end side:
https://apidev.fictadvisor.com/api#/Groups/GroupController_getGroupList

**Comment by Chopperino** [comment]
all functional requirements are met on the back-end side
