### ISSUE TITLE
[FEATURE] Transfer Captain role on Group tab on Account page

### ISSUE THREAD

**Issue by hoshion** [fictadvisor/fictadvisor#53]
The task consists of three parts:

- create Icon+Text Button according to the design in Figma, that opens pop-up. This button appears on the captain account in front of captain in the list:

![image](https://github.com/fictadvisor/fictadvisor/assets/42845566/5ce75eb2-5a2e-404e-85f7-c20915d196f7)

- create Pop-up window according to the design in Figma, where you can pick a user of the group (except of captain) and transfer Captain role. The button "transfer" should trigger endpoint on the back-end:

![image](https://github.com/fictadvisor/fictadvisor/assets/42845566/c1ffbc44-61ee-45ef-b5fa-373a9f23d3a1)

- check the efficiency of already created endpoint on the back-end side:
https://apidev.fictadvisor.com/api#/Groups/GroupController_switchCaptain

**Comment by kol-oss** [comment]
All functional requirements on back-end side are met and completely align with the specifications outlined in the task
