### ISSUE TITLE
[FEATURE] Create an admin grants flow

### ISSUE THREAD

**Issue by hoshion** [fictadvisor/fictadvisor#85]
We need to create "Search grants", "Edit grant", "Create grant" pages

## Front-end part

Search grants:

- Sidebar that is already implemented
- On the page there are rights only for some specific role (so the path will be fictadvisor.com/admin/roles/id-of-role/grants)
- Search panel:
  - Search input that searches by name of grant
  - Filter by status of grant (given or taken)
  - Sorting input with variants "by weight", "by name", "by status"
  - Icon button to change the direction of sorting (asc/desc)
- Button "Create" which opens "Create grant" page
- Table:
  - grant name (string)
  - weight (int)
  - status of right (given or taken)
  - Button "Edit" which opens "Edit grant" page
  - Button "Delete" which opens confirmation pop-up
  - Below the table there are settings for page size and page (from MUI component)

![image](https://github.com/fictadvisor/fictadvisor/assets/42845566/b6abaa56-586c-4695-a218-ade348e601e3)

Edit grant:

- Sidebar that is already implemented
- Button "Cancel" which opens "Search grants" page
- Button "Delete" which opens confirmation pop-up. After deleting opens "Search grants" page
- Button "Save" which send a request on back-end endpoint which saves data. After saving opens "Search grants" page
- Input for grant name (min 3, max 200)
- Input for weight (min 1, max 5000)
- Toggle button for status (given - true, taken - false)

![image](https://github.com/fictadvisor/fictadvisor/assets/42845566/cb9f17eb-be56-4a2f-b892-036b9adeffc4)

Create grant:

- Sidebar that is already implemented
- Button "Cancel" which opens "Search grants" page
- Button "Save" which send a request on back-end endpoint which saves data. After saving opens "Search grants" page
- Input for grant name (min 3, max 200)
- Input for weight (min 1, max 5000)
- Toggle button for status (given - true, taken - false)

![image](https://github.com/fictadvisor/fictadvisor/assets/42845566/72385941-68d7-4d3b-b690-1a0494f7c0f7)

## Back-end part

- Endpoint for getting grants for specific role (by id) that allow:
  - filter by:
    - status (taken, given)
    - name of grant
  - and sort by:
    - status
    - name of grant
    - weight

- Endpoint for creating grant on specific role (by id):
  - name (min 3, max 200)
  - weight (min 1, max 5000)
  - boolean value for status (given - true, taken - false)

- Endpoint for editing grant on specific role (by grant id):
  - name (min 3, max 200)
  - weight (min 1, max 5000)
  - boolean value for status (given - true, taken - false)
  
- Endpoint for deleting grant (by grant id)

**Comment by kovaliovev** [comment]
✔ QA approved
