### ISSUE TITLE
[BUG] Event without single repetition isn't created on the Schedule tab after submitting event creation form

### ISSUE THREAD

**Issue by kol-oss** [fictadvisor/fictadvisor#97]
**Preconditions:** User is authorized and can create events.

**Steps to reproduce**
1. Open the site https://fictadvisor.com/;
2. Go to the Schedule tab;
3. Click on the event creation button;
4. Fill the opened form and select repetition "Раз на 2 тижні" or "Раз на тиждень";
5. Click on the "Створити" button;
6. Pay attention to the schedule and error message.

**Actual result:** Event without single repetition isn't created on the Schedule tab after submitting event creation form.

```js
TypeError: Cannot set properties of undefined (setting 'description')
    at ScheduleService.createGroupEvent (/app/index.js:463717:34)
    at async ScheduleController.createEvent (/app/index.js:449608:24)
```

https://github.com/fictadvisor/fictadvisor/assets/62239358/d559cfb3-d339-44c4-867d-9307643dbff4

**Expected result:** Event with any repetition type is created on the Schedule tab after submitting event creation form.

**Environment:**
-deploy: prod;
-url: https://fictadvisor.com/schedule;
-OS: Windows 7;
-browser: Google Chrome 116.0.5845.141.

**Comment by hoshion** [comment]
Already fixed
